version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://neondb_owner:npg_Xr8HtlgIb2EM@ep-falling-rice-a8hgjpgh-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: npm run start:dev
    restart: unless-stopped